get_data_from_bigquery() takes 0 positional arguments but 1 was given
Traceback (most recent call last):
  File "C:\Users\vitor\OneDrive\Documentos\Projects\ControleFinanceiro\app\api\endpoints.py", line 14, in research
    return run_research(request.query,formatted_history)
  File "C:\Users\vitor\OneDrive\Documentos\Projects\ControleFinanceiro\app\services\opena_ai_service.py", line 33, in run_research
    raw_response = agent_executor.invoke({"query": query, "chat_history": formatted_history})
  File "c:\Users\vitor\OneDrive\Documentos\Projects\ControleFinanceiro\.venv\Lib\site-packages\langchain\chains\base.py", line 170, in invoke
    raise e
  File "c:\Users\vitor\OneDrive\Documentos\Projects\ControleFinanceiro\.venv\Lib\site-packages\langchain\chains\base.py", line 160, in invoke
    self._call(inputs, run_manager=run_manager)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\vitor\OneDrive\Documentos\Projects\ControleFinanceiro\.venv\Lib\site-packages\langchain\agents\agent.py", line 1624, in _call
    next_step_output = self._take_next_step(
        name_to_tool_map,
    ...<3 lines>...
        run_manager=run_manager,
    )
  File "c:\Users\vitor\OneDrive\Documentos\Projects\ControleFinanceiro\.venv\Lib\site-packages\langchain\agents\agent.py", line 1332, in _take_next_step
    for a in self._iter_next_step(
             ~~~~~~~~~~~~~~~~~~~~^
        name_to_tool_map,
        ^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        run_manager,
        ^^^^^^^^^^^^
    )
    ^
  File "c:\Users\vitor\OneDrive\Documentos\Projects\ControleFinanceiro\.venv\Lib\site-packages\langchain\agents\agent.py", line 1415, in _iter_next_step
    yield self._perform_agent_action(
          ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        name_to_tool_map, color_mapping, agent_action, run_manager
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\vitor\OneDrive\Documentos\Projects\ControleFinanceiro\.venv\Lib\site-packages\langchain\agents\agent.py", line 1437, in _perform_agent_action
    observation = tool.run(
        agent_action.tool_input,
    ...<3 lines>...
        **tool_run_kwargs,
    )
  File "c:\Users\vitor\OneDrive\Documentos\Projects\ControleFinanceiro\.venv\Lib\site-packages\langchain_core\tools\base.py", line 883, in run
    raise error_to_raise
  File "c:\Users\vitor\OneDrive\Documentos\Projects\ControleFinanceiro\.venv\Lib\site-packages\langchain_core\tools\base.py", line 852, in run
    response = context.run(self._run, *tool_args, **tool_kwargs)
  File "c:\Users\vitor\OneDrive\Documentos\Projects\ControleFinanceiro\.venv\Lib\site-packages\langchain_core\tools\simple.py", line 105, in _run
    return self.func(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: get_data_from_bigquery() takes 0 positional arguments but 1 was given

---
